### ISSUE TITLE
CRITICAL: Crash!!!11

### ISSUE THREAD

**Issue by DmitriyZaitsev** [Serduk/whatWhereWhen#118]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.sserdiuk.whatwherewhen.utilities.networkUtils.ChgkApi.chgkPojo.TournamentFeed.getTextId()' on a null object reference
        at com.sserdiuk.whatwherewhen.services.RequestingChGKService$LoadQuestionsToDB.run(RequestingChGKService.java:94)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by Serduk** [comment]
Fixed

**Comment by Serduk** [comment]
app crashed on Questions list activity. after tapping a lot tries to buttons in header (menu header)

**Comment by inndunas** [comment]
@Serduk @DmitriyZaitsev checked on 1.3.1, fixed.
